### ISSUE TITLE
Error: Looking up a deactivated widget's ancestor is unsafe

### ISSUE THREAD

**Issue by kamami** [bxqm/material_floating_search_bar#65]
I am getting this error when popping the route:

`The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.`

The error does not appear when I use the search before popping the route. It only occures when I go back and did not use the search at all.

Here is my simpliefied code:

        `class SearchBar extends StatefulWidget {
          const SearchBar({
            Key? key,
          }) : super(key: key);
        
          @override
          _SearchBarState createState() => _SearchBarState();
        }
        
        class _SearchBarState extends State<SearchBar> {

          final FloatingSearchBarController controller = FloatingSearchBarController();
          
            @override
            void dispose() {
              controller.dispose();
              super.dispose();
            }

          @override
          Widget build(BuildContext context) {
            return FloatingSearchBar(
              controller: controller,
              title: Text(
                "Aschaffenburg",
              ),
              hint: 'Suche einen Ort',
              builder: (context, _) {
                return Container();
              },
            );
          }
        }`

Any idea what I am doing wrong?

**Comment by bxqm** [comment]
No, the code looks fine and for me it works without problems when trying to reproduce. Are you sure that this error message is not caused by something else?
