### ISSUE TITLE
search bar radius does not imply when scrolling 

### ISSUE THREAD

**Issue by AnPhamThien** [bxqm/material_floating_search_bar#68]
![image](https://user-images.githubusercontent.com/66228093/145547533-3b3147f2-80b8-43da-8a4c-a21e7a418ecc.png)
![image](https://user-images.githubusercontent.com/66228093/145547632-1901c0a9-ce95-450a-9521-e1a815f8ebdc.png)

when scrolling, the bottom of the searchbar doesn't imply circular radius

**Comment by chicken349** [comment]
I have encountered the same issue and found that the reason of this is 

`  @override
  BorderRadius lerpBorderRadius() {
    if (spacing == 0.0) return super.lerpBorderRadius();

    return BorderRadius.lerp(
      borderRadius,
      BorderRadius.only(
        topLeft: borderRadius.topLeft,
        topRight: borderRadius.topRight,
        bottomLeft: **Radius.zero**,
        bottomRight: **Radius.zero**,
      ),
      scrollT,
    )!;
  }`

which is in src/floating_search_bar_transition.dart  line 217 - 231 for material_floating_search_bar 0.3.6.

I have changed the Radius.zero to borderRadius respectively, and overridden the package for my local use.
Steps for "Dependency overrides": [https://dart.dev/tools/pub/dependencies](url)

**Comment by bxqm** [comment]
Could show the code for your `builder` please?
