### ISSUE TITLE
using escape key to dismiss search bar

### ISSUE THREAD

**Issue by vipw** [bxqm/material_floating_search_bar#75]
I've started using this search bar in my web and desktop application, and would like to use the escape key to dismiss the search bar.

What do you think of the FloatingSearchBar constructor accepting an optional onKeyEvent function? 

The TextField could be parented in a KeyboardListener, and my callback would hide the search bar using the controller.,

**Comment by vipw** [comment]
Pull request for this feature: https://github.com/bxqm/material_floating_search_bar/pull/77

**Comment by bxqm** [comment]
Included in version `0.3.7`
